name: 'healthcare_provider_analytics_pipeline'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  healthcare_provider_analytics_pipeline:  # matches your project name
    +materialized: view                            # default for all models
    staging:
      +materialized: view                          # or table if you want
    intermediate:
      +materialized: table
    marts:
      +materialized: table
